[EHT-592] Sui validator setup
encapsulate-xyz/sui-ansible pull request #2
Opened 2024-12-14 12:36 UTC by kowshikvajrala

2024-12-14 14:35 UTC, aditya-manit requested changes
Port situations needs to be checked again

1. Please check configs again and fetch ports from group var, right now some of them are being are while other arent
2. Some ports requires only udp traffic while other tcp
3. Please check their docs if they have added anything on ports and ufw rules
4. Update services if needed from https://www.notion.so/encapsulate/Services-15c14f565a5080aa930df5ea6e550f19?pvs=4

2024-12-14 14:35 UTC, aditya-manit commented on roles/node/templates/mainnet/validator/config.yaml.j2
> +  external-address: /dns/{{ sui.validator.external_address }}/udp/8084
please store the port in group var

2024-12-14 14:35 UTC, aditya-manit commented on roles/node/templates/mainnet/validator/config.yaml.j2
> +json-rpc-address: 0.0.0.0:9000
This needs to be opened as well

2024-12-14 14:35 UTC, aditya-manit commented on roles/node/vars/ufw_rules.yml
> +  validator:
Please check once if they have anything on ports in their official docs

2024-12-14 14:35 UTC, aditya-manit commented on roles/node/templates/testnet/fullnode/config.yaml.j2
> +enable-event-processing: true
should be fetched from group vars

2024-12-14 14:39 UTC, aditya-manit commented on roles/node/templates/testnet/systemd.service.j2
> +ExecStart={{ node_bin_dir }}/{{ service_identifier }} --config-path {{ node_config_file_path }}
https://www.notion.so/encapsulate/Services-15c14f565a5080aa930df5ea6e550f19?pvs=4

2024-12-14 14:40 UTC, aditya-manit commented
I am merging this PR, lets address the comments in another bracnch

2024-12-14 14:40 UTC, merged

2024-12-17 06:57 UTC, kowshikvajrala commented on roles/node/tasks/main.yml
> +  ansible.builtin.get_url:
The name of sui cli binary is sui-bridge-cli ?